name: Deploy to PPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper dh-make gnupg dput

    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo -e "5\ny\n" | gpg --batch --yes --command-fd 0 --edit-key 441238F15933B87A95BE3CACF1B867E3E00AC6B8 trust

    - name: Build Debian package
      run: |
        mkdir -p build && cp -r src/* build/
        dpkg-deb --build build backlight_1.0_all.deb

    - name: Upload package to PPA
      env:
        PPA: your-ppa-name/ppa
        LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
        LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}
      run: |
        debsign -k ${LAUNCHPAD_USERNAME} backlight_1.0_all.deb
        dput ppa:${PPA} backlight_1.0_all.deb
