name: Deploy to PPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper dh-make gnupg dput build-essential

    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo -e "5\ny\n" | gpg --batch --yes --command-fd 0 --edit-key 441238F15933B87A95BE3CACF1B867E3E00AC6B8 trust

    - name: Build Debian package
      run: |
        cd src
        debuild -us -uc

    - name: Sign and upload package to PPA
      env:
        PPA: softcysec/ppa
        LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
        LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}
      run: |
        debsign -k 441238F15933B87A95BE3CACF1B867E3E00AC6B8 ../backlight_1.0-1_amd64.changes
        dput ppa:${PPA} ../backlight_1.0-1_amd64.changes
